Repository ZiyadAlHaqbani/restngo, pull requests merged in 2025-05, with the labels that each got.

#27 implementing DSL scanner, work in progress.
  .gitignore
  docs.excalidraw.png
  dsl/parser/astnode.go
  dsl/parser/parser.go
  dsl/scanner/scanner.go
  dsl/scanner/tokens.go
  main.go
Labels: enhancement

#53 add match constraint and tests
  constraints/match_constraint.go
  constraints/utils.go
  constraints/utils_test.go
  nodes/dynamic_node_test.go
  nodes/static_node_test.go
Labels: bug, enhancement

#51 removed duplicate runner files
  main.go
  runner/context.go
  runner/runner.go
Labels: bug

#62 Get set
  models/node.go
  nodes/conditional_node.go
  nodes/dynamic_node.go
  nodes/mock_node.go
  nodes/static_node.go
Labels: enhancement
